// qwik-app/src/components/TodoFilter/index.tsx
import type { QRL } from "@builder.io/qwik";
import { component$ } from "@builder.io/qwik";
import "./index.css";
import type { Status } from "~/routes";

type Props = {
  filterTodos: QRL<(status: Status) => void>;
};

export const TodoFilter = component$(({ filterTodos }: Props) => {
  return (
    <div class="todo_filter">
      <button
        type="button"
        class="todo_filter__button"
        onClick$={() => filterTodos("all")}
      >
        ALL
      </button>
      <button
        type="button"
        class="todo_filter__button"
        onClick$={() => filterTodos("active")}
      >
        ACTIVE
      </button>
      <button
        type="button"
        class="todo_filter__button"
        onClick$={() => filterTodos("completed")}
      >
        COMPLETED
      </button>
    </div>
  );
});

// vite-project/src/components/TodoFilter/index.tsx
import "./index.css";
import { Status } from "../Todo";

type Props = {
  filterTodos: (status: Status) => void;
};

export function TodoFilter({ filterTodos }: Props) {
  return (
    <div className="todo_filter">
      <button
        type="button"
        className="todo_filter__button"
        onClick={() => filterTodos("all")}
      >
        ALL
      </button>
      <button
        type="button"
        className="todo_filter__button"
        onClick={() => filterTodos("active")}
      >
        ACTIVE
      </button>
      <button
        type="button"
        className="todo_filter__button"
        onClick={() => filterTodos("completed")}
      >
        COMPLETED
      </button>
    </div>
  );
}
