// vite-project/src/components/TodoForm/index.tsx
import "./index.css";
import { ChangeEvent, FormEvent } from "react";

type Props = {
  onSubmit: (e: FormEvent<HTMLFormElement>) => void;
  onChange: (e: ChangeEvent<HTMLInputElement>) => void;
  todo: string;
};

export function TodoForm({ onSubmit, onChange, todo }: Props) {
  return (
    <form onSubmit={onSubmit} className="todo_form">
      <input
        type="text"
        name="todo"
        required
        className="todo_form__input"
        value={todo}
        onChange={onChange}
      />
      <button type="submit" className="todo_form__button">
        Add
      </button>
    </form>
  );
}

// qwik-app/src/components/TodoForm/index.tsx
import type { QRL, Signal } from "@builder.io/qwik";
import { component$ } from "@builder.io/qwik";
import "./index.css";

type Props = {
  onSubmit: QRL<() => void>;
  todo: Signal<string>;
};

export const TodoForm = component$(({ onSubmit, todo }: Props) => {
  return (
    <form preventdefault:submit onSubmit$={onSubmit} class="todo_form">
      <input
        type="text"
        name="todo"
        required
        bind:value={todo}
        class="todo_form__input"
      />
      <button type="submit" class="todo_form__button">
        Add
      </button>
    </form>
  );
});
